--- #YAML:1.0
name:                Games-Roguelike-Caves
version:             0.01
abstract:            generation of cave levels using cellular automata
license:             ~
author:              
    - Zach M <zach@nonet>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
